version: '3.7'
x-{{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
  volumes:
  - ./local.py:/code/src/{{cookiecutter.flask_settings.replace('.', '/')}}/local.py
  image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
services:
  nginx:
    restart: unless-stopped
    ports:
    - 80:80
  {{cookiecutter.app_type}}:
    restart: unless-stopped
    <<: [ *{{cookiecutter.app_type}} ]
    ports:
    - "8000:8000"
  {% if not cookiecutter.remove_cron %}
  cron:
    restart: unless-stopped
  {%- endif%}
  backup:
    restart: unless-stopped
  mailcatcher:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  db:
    restart: unless-stopped
  backup:
    restart: unless-stopped
{% if cookiecutter.db_mode == 'postgres' %}  setup-postgres:
    restart: unless-stopped
{% endif %}
