version: '3.7'
x-{{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
  volumes:
  - ./local.py:/code/src/{{cookiecutter.flask_settings.replace('.', '/')}}/local.py
  image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
services:
{% if cookiecutter.with_nginx %}  nginx:
    restart: unless-stopped
    ports:
    - 80:80{%endif%}
  {{cookiecutter.app_type}}:
    restart: unless-stopped
    <<: [ *{{cookiecutter.app_type}} ]
    ports:
    - "5000:5000"
  {% if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    restart: unless-stopped
  {%- endif%}
{%- if cookiecutter.with_mailcatcher%}  mailcatcher:
    restart: unless-stopped{%endif%}
{% if cookiecutter.redis_image %}  redis:
    restart: unless-stopped{%endif%}
{% if cookiecutter.db_mode  %}  db:
    restart: unless-stopped
  backup:
    restart: unless-stopped
{% if cookiecutter.db_mode == 'postgres' %}  setup-postgres:
    restart: unless-stopped
{% endif %}{% endif %}
