version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args:
        PY_VER: "${FLASK_PY_VER:-{{cookiecutter.py_ver}}}"
        WITH_IMPOSM: "${FLASK_WITH_IMPOSM:-{{cookiecutter.with_imposm}}}"
        PYCHARM_VERSION: "${PYCHARM_VERSION-}"
        VSCODE_VERSION: "${VSCODE_VERSION-}"
        WITH_VSCODE: "${WITH_VSCODE:-0}"
        WITH_PYCHARM: "${WITH_PYCHARM:-0}"
        BASE: "${FLASK_BASE_IMAGE:-corpusops/ubuntu-bare:bionic}"

services:
  {%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
