version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args:
        PY_VER: "${FLASK_PY_VER:-{{cookiecutter.py_ver}}}"
        WITH_IMPOSM: "${FLASK_WITH_IMPOSM:-{{cookiecutter.with_imposm}}}"
services:
  {%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
